name: 反馈错误文本
description: 如果您发现了翻译中的错误或问题，请在此处报告。
labels: [error]
body:
  - type: input
    id: error-description
    attributes:
      label: 描述
      description: 对错误或问题的简洁描述。
      placeholder: 描述错误或问题
    validations:
      required: true
  - type: textarea
    id: error-details
    attributes:
      label: 详细描述
      description: 请提供更多详细信息，以便我们了解问题的具体情况。
      placeholder: 在此处添加详细描述
    validations:
      required: true
  - type: textarea
    id: error-screenshot
    attributes:
      label: 截图（可选）
      description: 如果可能，请提供与错误相关的截图。
      placeholder: 拖放截图文件或粘贴截图的链接
  - type: checkboxes
    id: error-confirmations
    attributes:
      label: 确认
      description: 在提交反馈之前，请确认以下内容：
      options:
        - label: "我已经确认了文本翻译是否准确，并且确定问题确实存在。"
          required: true
        - label: "我已经搜索了现有的错误报告，以确保我没有重复提交相同的问题。"
          required: true
  - type: markdown
    attributes:
      value: |
        ## 感谢您的反馈！

        我们将尽快处理您的问题，并尽力改进翻译质量。
