name: 兼容性问题
description: 报告与第三方插件冲突的问题
title: "[兼容性] "
labels: ["compatibility"]
body:
  - type: input
    id: plugin
    attributes:
      label: 冲突插件
      placeholder: 例如 Cactbot - Raidboss
    validations:
      required: true

  - type: dropdown
    id: method
    attributes:
      label: 使用的汉化方式
      options:
        - 汉化工具 (FFXIVChnTextPatch-SM.exe)
        - Penumbra Mod (.pmp)
        - 文件覆盖 (overwrite.zip)
    validations:
      required: true

  - type: textarea
    id: conflict
    attributes:
      label: 冲突表现
      description: 具体哪些功能无法使用、报错或表现异常
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      description: 如何触发冲突
    validations:
      required: false
